- lsstseries/__init__.py
- lsstseries/timeseries.py
- setup.py
The first stab at an underlying data structure is a multi-indexed pandas dataframe, where the band+an integer index describe the indexing scheme, and the flux, flux error, and time are the included data columns.
Included a from_dict I/O routine, which may or may not be useful in the long term, but is useful in the very short term.
Properties were added to allow easy access to the data columns/band index, but the multi-indexing may require these to be a bit more complex (option for band specific properties?)
I'd propose an initial convention for package shorthand as: 
`import lsstseries as ls`
> Initial work on the underlying data structure + Package Setup

- lsstseries/ensemble.py
- lsstseries/timeseries.py
This PR includes a *rough* implementation of the ensemble class, which is the object that contains many lightcurves. This is distinct from the timeseries class, which holds the information of one lightcurve, indexed by band and an arbitrary integer index. The ensemble is essentially just one additional index level, based on an object id, which allows index slicing to return individual light curves.
The implementation here focuses on IO and particularly the use case of pulling data down from the TAP: https://data.lsst.cloud/api-aspect . A token is needed to query against TAP, the link explains how to generate one.
As I mention above, I think this implementation is somewhat rough. The initial challenge with trying to emulate a LightKurve like approach for lsstseries is that with TAP we are …
> Ensemble Initial Implementation

- lsstseries/ensemble.py
Modifies the translation from flux to mag quantities so that flux_err gets translated into a query for scisql_nanojanskyToAbMagSigma that takes both flux and flux_err.
The function is getting cumbersome with two if_else statements - in the future we might want to reconsider this approach.
> Modify TAP query to correctly catch mag_err values

- lsstseries/analysis/structurefunction2.py
- lsstseries/ensemble.py
- lsstseries/timeseries.py
- tests/test_analysis.py
- tests/test_ensemble.py
This PR is the first set of enhancements to the structurefunction2 implementation in lsstseries. This addresses some of the requirements listed in #22 and #23, but I wanted to check in at this stage to make sure everything is on the right track.
What's in this PR:
* Ability to operate on many lightcurves, either independently in batch mode, or with combination to have multiple lightcurves contribute to the same result
* Some nan filtering, to make sf2 runnable in ensembles that have not had nans handled
* Improved output, a pandas dataframe is now returned. ensemble.batch has been improved to allow the dask meta keyword (which defines the output structure) to be passed, but also provides a baked-in solution for calc_sf2.
* Automated binning, implemented 3 options. "size" solves for bins …
> First Set of Structure Function Enhancements

- tests/test_ensemble.py
Change the `parquet_data` fixture to stop the client in the ensemble made in the fixture after the test runs.
> Teardown ens dask client to fix #28

- src/lsstseries/ensemble.py
- tests/lsstseries_tests/conftest.py
- tests/lsstseries_tests/test_analysis.py
- tests/lsstseries_tests/test_ensemble.py
- Allows for a single dask client to be created for all unit tests. This speeds up execution and reduces warnings.
- Locally, unit test execution goes from 35-45 seconds to 8-9 seconds
- In github CI, execution goes from 67-77 seconds to 16-19 seconds
- Addresses nearby black formatting and pylint warnings
> Inject dask client into ensemble

- src/lsstseries/ensemble.py
- tests/lsstseries_tests/test_ensemble.py
Discourages access to the dataframe directly (ensemble.data -> ensemble._data), adds wrapper functions for a set of core functionalities. Initially intended to add a wrapper for visualize(), which returns an image of the dask task graph, but was scared off by taking on the graphviz dependency for now.
Resolves #41
> Core wrappers

- src/lsstseries/ensemble.py
- tests/lsstseries_tests/test_ensemble.py
By default, use map_partitions instead of an ensemble-wide groupby. Though the ensemble-wide groupby is still available to use if use_map is set to false. Map partitions creates more efficient task graphs and avoids data shuffling costs, but has the added requirement that each light curve is confined to a single partition.
Closes #19
> Map partitions

- src/lsstseries/analysis/stetsonj.py
Add option to filter nans in calc_stetson_J. It's available in calc_sf2, and so the same functionality should be available in calc_stetson_J
> add nan filtering

- src/lsstseries/ensemble.py
Ensemble.batch passes the data columns along to analysis functions as pandas.series objects, as our analysis functions are designed to consider 1d array-like inputs, this can introduce a sizeable slowdown. By casting these series objects to numpy arrays, we see speedups of ~10x when testing on calc_stetson_J. Calc_sf2 does not benefit from the change, but that's potentially because of #46
> convert series to numpy arrays in batch function

- src/lsstseries/analysis/structurefunction2.py
- tests/lsstseries_tests/test_analysis.py
Replacing `qcut` with numpy `quantile` leads to a >8x speedup. Since we are only using the bins from the `cut` function, we can replace those with a `linspace`.
There is some extra logic to ensure this is a complete no-op (pandas extends the lower bound of the fit bin in the cut function by 0.1% of the range). I'm not sure if we need to keep that or not. But including it right now for consistency.
> Replace the Pandas cut and qcut with numpy functions

- docs/notebooks/scaling_to_large_data.ipynb
- docs/notebooks/working_with_the_ensemble.ipynb
- src/lsstseries/ensemble.py
- tests/lsstseries_tests/test_ensemble.py
This PR implements the Object Source Refactor, where the _data dataframe has been split into the _object and _source dataframes.
Main Highlights:
* _object and _source under the hood, many dataframe utility functions now include the `table` arg for picking which table to operate on, e.g. `ensemble.head(table="object", 5)`
* Both the _source and _object tables have a dedicated dirty flag, which indicates when they've been modified. Operations that access data from either of the tables will first check the dirty flags to see if a sync operation should be done. Syncs don't need to be done when pulling from a dirty table, only when you need to pull from the other table. For example, if I trim NaNs from source, source is now dirty, if I then want to load the object table then I will need to …
> Object Source Refactor

- src/lsstseries/ensemble.py
- tests/lsstseries_tests/test_ensemble.py
Add insert to allow the insertion of fake data points for testing or one-off analysis. This is not a particularly fast function as it may need to repartition the data, so it should not be used as part of a core loop.
> Add an insertion operation for the Ensemble

- src/lsstseries/ensemble.py
- tests/lsstseries_tests/test_ensemble.py
This PR addresses issue #75. Creates an optional parameter that allows `_generate_object_table` to keep any object ids are no longer in the `_source` table but were previously in the `_object` table. It populates all counts for these objects with zero.
> Give _sync_tables the ability to persist objects that have no sources 

- pyproject.toml
- src/lsstseries/analysis/structurefunction2.py
- tests/lsstseries_tests/test_analysis.py
The actual logic here is relatively small (and so hopefully safe). Most of this PR is adding unit tests.
> Allow users to not pass timestamps into SF2 function

- src/lsstseries/analysis/structure_function/base_calculator.py
- src/lsstseries/analysis/structure_function/basic/calculator.py
- src/lsstseries/analysis/structurefunction2.py
- src/lsstseries/ensemble.py
- tests/lsstseries_tests/test_analysis.py
The vast majority of this PR is organizing argument validation in `structurefunction2.py`. You'll see calls to functions named `_validate_<arg>`. In each of those we'll take a look at the input arguments and possibly the values found in argument_container as well, and take the one with the highest priority. 
Additionally we may do some comparison checks and raise exceptions if the inputs are not well formed. i.e. number of elements in `band` doesn't match number of elements in `flux` arrays.
But to address the title of the PR, this work also allows users:
- Pass nothing at all for `lc_id` (`None` will be the default)
- Pass `None` for `lc_id`
- Pass an array for `lc_id`
- Pass `lc_id` inside of the argument container
and 
- Pass nothing at all for `band` (`None` will be the default)
- …
> Adding support to allow users to pass `None` for lc_id and/or band

- src/lsstseries/analysis/structure_function/base_calculator.py
- src/lsstseries/analysis/structure_function/basic/calculator.py
- src/lsstseries/analysis/structure_function/macleod_2012/calculator.py
This does not address issue #102, it is only an effort to reduce code duplication. All of the unit test are untouched, and pass as expected. 
The long story is that after implementing the first Structure Function calculator, I didn't know what code would likely be duplicated. But after implementing the second, I spotted some of the duplication. Thus in an effort to reduce that duplication, this PR was created.
> Move duplicated binning logic out of the SF child classes into parent class.

- .pre-commit-config.yaml
Updates to the sphinx configuration for the pre-commit hook weren't correctly applied when I updated the copier template last time. This PR fixes that. 
I also noticed that the new subclasses of Structure Function calculator class weren't being picked up by AutoAPI - I needed to add a __init__.py file to the directories so they would identified and included.
> Correct pre-commit sphinx configuration, add __init__ files.

- src/lsstseries/analysis/structure_function/base_calculator.py
- tests/lsstseries_tests/structure_function_calculators/test_bauer_2009a_calculator.py
- tests/lsstseries_tests/structure_function_calculators/test_bauer_2009b_calculator.py
- tests/lsstseries_tests/structure_function_calculators/test_schmidt_2010_calculator.py
- tests/lsstseries_tests/test_analysis.py
In the main branch after we have established the bins for the time differences, we return the bin centers to the user as the parameter `dts`. However, in practice this value can be misleading, and it is more useful to return the mean of the values in a given bin as the parameter `dts`. 
This PR represents the work to gather those statistics for the bins. There were several unit tests that needed to be updated as well, but because we were using small, contrived examples, it was not difficult to verify that the new `dts` values were correct.
> Return `mean(delta_t values in bin)` as `dts` for Structure Function

- src/lsstseries/analysis/structure_function/base_calculator.py
- tests/lsstseries_tests/structure_function_calculators/test_base_calculator.py
- tests/lsstseries_tests/test_analysis.py
- tests/lsstseries_tests/test_ensemble.py
In the non-combined mode of Structure Function calculations, we would ignore user provided bins in the `argument_container` and instead always calculate the bins. This PR fixes that bug and introduces regression unit tests.
> Fixes bug that causes Structure Function to ignore user provided time bins.

- src/lsstseries/analysis/structure_function/base_calculator.py
- src/lsstseries/analysis/structure_function/basic/calculator.py
- src/lsstseries/analysis/structure_function/bauer_2009a/calculator.py
- src/lsstseries/analysis/structure_function/bauer_2009b/calculator.py
- src/lsstseries/analysis/structure_function/macleod_2012/calculator.py
- src/lsstseries/analysis/structure_function/schmidt_2010/calculator.py
- tests/lsstseries_tests/structure_function_calculators/test_macleod_2012_calculator.py
I realize that this PR looks nasty. 
Each of the different Structure Function calculator methods had a large block of duplicated code that has now been consolidated into base_calculator. 
Prior to starting on the work to subsample and bootstrap the data (issue #61), it is necessary to consolidate the code to avoid making complicated changed in 5 different places. 
It's good to note that all the unit tests still pass despite this large change, and now, there's 1/5 the amount of code to maintain.
> Consolidate duplicated Structure Function code into `base_calculator.py`.

- docs/notebooks/working_with_the_ensemble.ipynb
- src/lsstseries/ensemble.py
- tests/lsstseries_tests/test_ensemble.py
Add filter operations for the tables by wrapping Dask DataFrame's `query` function and the ability to pass a series of Booleans.
Also adds a `_lazy_sync_table` function to simplify the logic when you only need to modify one table.
> Add filter operations

- docs/notebooks/working_with_the_ensemble.ipynb
- pyproject.toml
- src/lsstseries/ensemble.py
- tests/lsstseries_tests/test_ensemble.py
Wrap Dask's `assign` function to allow users to construct new columns in either the source or object table.
Closes #44 
Also addresses part of #64
> Wrap Dask's Assign function

- docs/requirements.txt
- pyproject.toml
readthedocs has been failing builds since the sf showcase notebook went in (slightly concerning that our CI didn't catch this), at least one layer of this is that Numba needs Numpy <= 1.24.0, updated that for the docs requirements.
> downgrade numpy for numba support

- src/tape/analysis/structure_function/bauer_2009a/calculator.py
- src/tape/analysis/structure_function/bauer_2009b/calculator.py
- src/tape/analysis/structure_function/macleod_2012/calculator.py
- src/tape/analysis/structure_function/schmidt_2010/calculator.py
- tests/tape_tests/structure_function_calculators/test_bauer_2009a_calculator.py
- tests/tape_tests/structure_function_calculators/test_bauer_2009b_calculator.py
- tests/tape_tests/structure_function_calculators/test_macleod_2012_calculator.py
- tests/tape_tests/structure_function_calculators/test_schmidt_2010_calculator.py
- tests/tape_tests/test_analysis.py
Fixes https://github.com/lincc-frameworks/tape/issues/165, makes all calculators to return SF^2, instead of SF^1 for ``non-basic'' calculators.
> SF^1 to SF^2 bug fix

- src/tape/ensemble.py
The smoke tests started failing a few days ago. The culprit was the calc_stetson_J function, which returns a dictionary, was interacting poorly with the default meta assigned by ens.batch(). The default meta took the index columns string type and projects that onto the result, turning the dictionary into a string. In the long term, we should have calc_stetson_J return an object that is able to be coerced into a dataframe (maybe it already is?), but for now the meta assignment that defaults to the type of the ID column is probably not ideal, and we should instead expect floats as a general result.
> update default meta

- src/tape/analysis/structure_function/sf_light_curve.py
- tests/tape_tests/test_analysis.py
Fixes bug in the bootstrapping method, by changing stochastic sampling to be done with replacement. Prerequisite for [Issue 180](https://github.com/lincc-frameworks/tape/issues/180).
> changed replace False to True in random_generator

- .github/workflows/linting.yml
- .github/workflows/smoke-test.yml
- .github/workflows/testing-and-coverage.yml
Closes #187
Added Python 3.11 to the version matrix on Github Actions' config files.
All Github Actions checks should succeed on this PR, including new checks for linting, testing / coverage and smoke tests on Python 3.11
> Add support for Python 3.11 on Github Actions

- src/tape/analysis/structure_function/base_argument_container.py
- src/tape/analysis/structure_function/base_calculator.py
- src/tape/analysis/structure_function/sf_light_curve.py
- src/tape/analysis/structurefunction2.py
- tests/tape_tests/test_analysis.py
Fixes #180 
- Introduced `estimate_err` argument; when it is true the errors are estimated via bootstraping
- do 100 repetitions by default  
- Renamed `_equally_weight_lightcurves` function to `_bootstrap` function
- Changed behavior depending on the bool value of `_equally_weight_lightcurves` argument
- if self `_equally_weight_lightcurves = True` then go and take `[min(self._difference_values_per_lightcurve)]` on from each lightcurve
- if self `_equally_weight_lightcurves = False` then select all of the differences avaliable
- Modified test results
> Dedicated error estimate in structure function

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Adds a function for converting a flux column to a magnitude column. Requires a zero point column to be additionally supplied. Errors are propagated if a error column is provided. Implements #183.
> Flux to Mag Converter Function

- .github/workflows/linting.yml
- .github/workflows/smoke-test.yml
- .github/workflows/testing-and-coverage.yml
Drops support for Python 3.8 as per #204
> remove python 3.8 from workflows

- src/tape/ensemble.py
This is a quick fix of a little bug in `Ensemble.batch`. However it would be nice to have better test coverage for `on` argument, which this PR does not provide
Closes #202
> Fix how Ensemble.batch processes on=None/str

- src/tape/__init__.py
- src/tape/ensemble_frame.py
- tests/tape_tests/conftest.py
- tests/tape_tests/test_ensemble_frame.py
Introduces the EnsembleFrame, a minimal subclass extending the Dask Dataframe as proposed in [issue #192](https://github.com/lincc-frameworks/tape/issues/192). A barebones EnsembleSeries is included as well.
In order to correctly propagate the metadata that Dask uses when instantiating dataframes, the TapeFrame and TapeSeries Pandas subclasses are provided as well.
Note that [dask-geopandas](https://github.com/geopandas/dask-geopandas/) was used as a model extending the Dask dataframe.
> A minimal Dask Dataframe subclass for the Ensemble

- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- tests/tape_tests/conftest.py
- tests/tape_tests/test_ensemble.py
- tests/tape_tests/test_ensemble_frame.py
Moves `Ensemble.convert_flux_to_mag()` into the `EnsmebleFrame`
This PR should close [issue #192](https://github.com/lincc-frameworks/tape/issues/192)
> Make convert_flux_to_mag part of the EnsembleFrame

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Provides methods for an `Ensemble` to track `EnsembleFrames` (a subclass of Dask Dataframes), supporting functionality to add, update, drop, select, and print info about the frames. 
Each `EnsembleFrame` object is tracked by a user-provided string label. However "source" and "object" are reserved labels for the respective source and object tables. Though these are not currently populated by the `Ensemble` loader functions, we go ahead and prevent the user from adding, updating, or removing frames tracked with those reserved labels.
This functionality was proposed in [issue #193](https://github.com/lincc-frameworks/tape/issues/193).
> Ensembles can now track a group of labeled frames

- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble_frame.py
A small fix for `EnsembleFrame.assign()` to correctly propagate the `label` and `ensemble` fields. This appears in calls to `EnsembleFrame.convert_flux_to_magnitude` but was overlooked in the initial testing. Fixed by adding `tape._Frame.assign` which just calls the parent and propagates metadata like we do in `tape._Frame.copy`
> Preserve EnsembleFrame metadata after assign()

- src/tape/ensemble.py
- tests/tape_tests/conftest.py
- tests/tape_tests/test_ensemble.py
Adds the loader functions `Ensemble.from_pandas` and `Ensemble.from_dask_dataframe`. This allows the user to provide TAPE with their own Pandas or Dask dataframes constructed via their own preferred sources and I/O as outlined in issue [#223](https://github.com/lincc-frameworks/tape/issues/223).
`Ensemble.from_source_dict` and `Ensemble.from_parquet` were simplified with some of their functionality moved into `Ensemble.from_dask_dataframe`.
> Support loading ensemble from pandas and dask dataframes

- docs/requirements.txt
- docs/tutorials.rst
- docs/tutorials/using_ray_with_the_ensemble.ipynb
- pyproject.toml
Adds a tutorial on using dask_on_ray with the Ensemble. No code changes are needed to TAPE itself to work with this.
> adds a dask_on_ray tutorial

- src/tape/ensemble.py
In _sync_tables, the object to source sync involves a full merge between object and source, and then a drop of all remaining object columns. This PR simplifies this by just applying map_partitions to filter down the source dataframe based matches to the object index. It should be about 2x faster.
Science Driver Impact:
The current implementation was causing issues with the single pixel dataset for the Time-Domain MVP project, where _sync_tables was erroring out (int casting error with the residual NaN columns from the merge) whenever the object table was included. The new implementation seems to handle the single-pixel dataset well.
> Streamline Object->Source Sync

- src/tape/ensemble.py
A few weeks ago, the smoke tests failed on the current coalesce function. The initial fix I applied involved resetting the index, which is generally an expensive operation in Dask. This should be a better way to handle things, where we just apply map_partitions to coalesce on a partition-by-partition basis.
Science Driver Impact:
The initial fix to the smoke tests made the coalescing function have issues with the TAPE single pixel dataset for the time-domain MVP, particularly it complained about needing to know the divisions when resetting the index. This new implementation works successfully with the TAPE single-pixel dataset.
> coalesce with map_partitions

- src/tape/ensemble.py
- tests/tape_tests/conftest.py
- tests/tape_tests/test_ensemble.py
In the loader method `from_dask_dataframe`, we were mistakenly not updating the object table's index in the case where the object table is supplied as an argument rather than generated from the source table.
Unit tests are updated based on the identifying issue [#230](https://github.com/lincc-frameworks/tape/issues/230) validating the case where the object table isn't generated and that analysis functions can be called on the generated  ensemble.
> Set object table index for from_dask_dataframe

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Motivated by Pan-STARRS1 zero_point calculations. Currently, the zero_point needs to be a column of the source table. But it seems clear from some limited examples that users will often want to just provide a float here.
> Adds ability to give a single float input to zero_point

- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble_frame.py
Fixes issue where `EnsembleFrame.set_index` does not correctly set a named index.
As an example, `EnsembleFrame.set_index("id")` would fail to produce an `EnsembleFrame` with an index named "id". This would not immediately fail, but performing `groupby["id"]` on the resulting frame would result in a key error since we dropped the column and our index is unnamed. Such a test case has now been added in this PR.
In the previous behavior, the calls to `set_index` eventually produce a call to `dask.dataframe.core.map_partitions` and the incorrect index is constructed in [`_get_meta_map_partition`](https://github.com/dask/dask/blob/216c7c9393d8df1014a911eceb797502999e8a51/dask/dataframe/core.py#L7066). Here the meta is overridden with an incorrect index in the call to
```
meta_index = …
```
> Fix EnsembleFrame.set_index

- docs/requirements.txt
- pyproject.toml
Noticed this while working on my dash; unpinning sphinx to address doc build failure (see https://github.com/lincc-frameworks/python-project-template/issues/294)
> Update requirements.txt to unpin sphinx

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Adds a function to calculate the number of observations in source, with option to do it just for the total, or the total and a count for each band.
Addresses #246.
> add calc_nobs

- docs/requirements.txt
- pyproject.toml
- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble.py
Adds support for `EnsembleFrame.update_ensemble()` and uses the `ObjectFrame` and `SourceFrame` objects throughout the ensemble. 
Note that in order for `_generate_object_table()` to work we also needed to add `ObjectFrame.from_dask_dataframe` to create an `ObjectFrame` from the generated dask table. 
We also move the fields for whether an object or source table is "dirty" into fields within the EnsembleFrames themselves.
> Add update_ensemble() and Use EnsembleFrames

- tests/tape_tests/test_ensemble.py
Removed reference to Ensemble._nobs_band_cols field
> Fixed failing unit test

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Small bug fix for the sync PR that just went in.
> fix bug in sync

- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble_frame.py
When transformations on an `EnsembleFrame` create a new object, its `_is_dirty` status isn't copied to the new object. We move the field into its parent `_Frame` class so it can be copied in `_Frame._propagate_metadata`
Also ensures that we track `EnsembleFrame` metadata (label, parent ensemble, and now `_is_dirty`) across merge, drop, and persist calls.
> Propagate EnsembleFrame._is_dirty

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
If `Ensemble.update_frame` receives a frame which it currently tracks, it should mark the frame as dirty if the number of rows has changed. (Note that there may be further criteria which can be added in the future.)
Note that in addition to calls to this method by the user, `Ensemble.add_frame` and `EnsembleFrame.update_ensemble` are implemented by calling this method.
> Have update_frame mark frames as dirty

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Throughout the Ensemble, we manually mark frames as dirty for operations that we expect to change the number of rows such as dropna. In PR https://github.com/lincc-frameworks/tape/pull/267, we Ensemble.update_frame perform this whenever the Ensemble has been updated with a frame with a different number of rows. This allows us to remove manual calls to set_dirty throughout the Ensemble since operations like dropna use Ensemble.update_frame to store their results.
Note that the previous sync tests called dropna despite no NaNs being present in the table. Since now dropna only marks the table as dirty when rows are actually dropped, the test tables were modified to include a NaN value. Otherwise the testing strategy is to just rely on existing tests.
> Remove calls to set_dirty in ensemble

- pyproject.toml
- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
This PR addresses #275, adding two functions (`check_sorted` and `check_lightcurve_cohesion`) that assess whether the ensemble data is sorted and whether the source data is co-located within single partitions (referring to this as "cohesion"). 
There's a bit of a snowball effect to implementing these, so this ends up addressing #242 by adding a `sort` flag to loader calls that defaults to False. This allows the Ensemble to actually be unsorted, making the `check_sorted` function useful. The sort flag was added to Dask in 2023.6.1, so I've also updated the minimum version to this in `pyproject.toml`, this broke something in `ensemble.insert_sources`, where a small tweak is needed to the ColumnMapper and sorting needs to be on for it and potentially any upstream data loading. This may be …
> add check functions

- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble_frame.py
Previously `_Frame._propagate_metadata` called `result.set_dirty(self.is_dirty)` rather than `result.set_dirty(self.is_dirty())`.
This meant that when a transformation was performed on a dataframe, the result frame would return the bound *method* `is_dirty` itself rather than the boolean value returned by that method. In python, a boolean expression operating on a method itself interprets the method as `True`, resulting in unexpected cases where a transformed frame would incorrectly evaluate as dirty. This is fixed and some fields are renamed to avoid confusion.
In addition, `map_partitions` is overridden to propagate metadata if the output of the provided function is another` _Frame` object.
> Fix EnsembleFrame.set_dirty and map_partitions metadata propagation

- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble.py
Previously a call to`EnsembleFrame.update_frame(x)` for frame `x` would check if that frame was previously tracked, and if the row count had changed, would mark `x` as a dirty frame.
However, getting the row count through calls to `len` on a Dask dataframe can alter the task graph and cause lazy operations to be evaluated earlier. This was in particular causing significant slowdown in _sync_tables on a test notebook by forcing some lazy operations to be performed earlier. 
Here we move the calls to `set_dirty` to our methods wrapping Dask dataframe operations, including a new wrapper for `dropna`.
This may result in an increase in the number of syncs since even a `dropna` call on a table with no "na" values will now mark the table as dirty. However it should not result in more syncs than …
> Ensemble.update_frame no longer infers if a frame is dirty by checking if row count changed

- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble.py
`Ensemble.batch` should track a result dataframe when the `label` parameter is used, and it should correctly translate the meta for the batch operation to be either an `TapeFrame` or `TapeSeries` (which Dask will use to map the batched result to either be an `EnsembleFrame` or `EnsembleSeries` respectively).
Note that `Ensemble.batch` still returns the result frame rather than the `Ensemble` to keep the API backwards compatible, but we can later have it return the `Ensemble` object to allow for easier chaining of commands.
Fixes a bug for creating meta for a non-empty EnsembleSeries.
> Support storing batch results for custom meta

- src/tape/ensemble.py
- tests/tape_tests/conftest.py
- tests/tape_tests/test_ensemble.py
This PR does a few things that maybe I should have split up into different PRs, but there's also a decent amount of overlap. In this PR, I added more explicit support for Dask Divisions. In particular, checking if they are set after loading in data and warning the user if they are not. Divisions are also checked during sync operations to enable a new completely lazy sync that doesn't need to load the index fully into memory. In addition, the object table generation off the source table has been made lazy as well, removing the current unscalable implementation that loads the entire index into a pandas dataframe.
> Check Divisions, Enable Lazy Sync Operations on Divisions-enabled Ensembles, Overhaul Object Table Generation

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Addresses #287. Makes calc_nobs use map partitions to propagate metadata instead of groupby when divisions are known. This introduces an annoying cost of having to calculate the unique bands for the resulting meta in the by_band=True case, it's slow, but works for now.
> Calc nobs divisions

- docs/tutorials/binning_slowly_changing_sources.ipynb
- docs/tutorials/scaling_to_large_data.ipynb
- docs/tutorials/structure_function_showcase.ipynb
- docs/tutorials/tape_datasets.ipynb
- docs/tutorials/using_ray_with_the_ensemble.ipynb
Updates remaining TAPE documentation notebooks for the refactor, primarily consisting of replacing references to `Ensemble._source` and `Ensemble._object` with `Ensemble.source` and `Ensemble.object` respectively. No changes to the structure or functionality of the notebooks are made.
> Update Remaining TAPE Documentation Notebooks for the Refactor

- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble.py
When `Ensemble.object.compute()` or `Ensemble.source.compute()` are called we would like to give the `Ensemble` a chance to perform an Object-Source table sync prior to computing the result.
Some previously tested workflows had other functions triggering syncs at the appropriate times (such as `Ensemble.batch`) or were using `Ensemble.compute()`. Now calling `EnsembleFrame.compute` should trigger any potential syncing for the tracking `Ensemble`.
Currently, we're preserving both the refactored `EnsembleFrame` API and the `Ensemble` API, so with this change I also update several unit tests to be parameterized to use both the refactored and 'legacy' methods (both `Ensemble.compute` and `EnsembleFrame.compute`, both`Ensemble.dropna` and `EnsembleFrame.dropna`, etc.) This is a bit awkward, …
> Allow EnsembleFrame.compute to Trigger Object-Source Table Syncing

- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble_frame.py
Overrides [`dask.dataframe.DataFrame.join`](https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.join.html) so that we explicitly propagate metadata.
This fixes an error that happens when syncing tables with `known_divisions` introduced by merging PR https://github.com/lincc-frameworks/tape/pull/288 into this refactor branch from main.
Also note that `frame1.join(frame2)` will yield a result of type `frame1` regardless of the value of the `how` parameter and explicit testing of this is added here.
> Add Explicit Metadata Propagation for EnsembleFrame joins 

- src/tape/__init__.py
- tests/tape_tests/test_packaging.py
Addresses #137, looks like we were just missing the one line in the init, as setuptools already dynamically generates a _version.py file.
(Should be completely non-conflicting with the refactor)
> Add version

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
In https://github.com/lincc-frameworks/tape/pull/283, we introduced logic to allow for lazy syncing of tables with known divisions. This was accomplished via a [`join`](https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.join.html) call which was a left join by default.
However since we always sync the object table before the source table, it's possible to create an arrangement of operations values removed from the source table's index can be synced back from a dirty object table. This PR updates `test_ensemble.test_sync_tables` to have such a failing case and fixes it by switching to inner joins.
> Fix table syncing to use inner joins.

- docs/tutorials/working_with_the_ensemble.ipynb
- src/tape/analysis/feature_extractor.py
- tests/tape_tests/test_feature_extraction.py
Currently, `FeatureExtractor` analysis function requires `band_to_calc` parameter to specify passband it would pre-filter light curve on. This PR introduces `band_to_calc=None`, which tells the function to ignore passband information and apply the function to the whole light curve.
This option could be useful to some types of analysis, for example `light_curve.OtsuSplit` is not so sensitive to passband if it is applied to differential fluxes.
Another use case is datasets where each object is observed in a single passband, for example ZTF DRs. In such cases it could be practically useful to ignore passband information.
This PR is related to #317, but covers feature extraction only. `FeatureExtractor` could should be revisited again if/when #317 is implemented.
Fixes #323
> Allow to ignore band with FeatureExtractor

- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Resolves #332.
Adds a convenience function to grab a random lightcurve from the Ensemble, which we expect users to use to do quick sanity checks that operations have had the desired effect on their lightcurves.
> Adds a random lightcurve selection function to the Ensemble

- docs/tutorials/working_with_the_ensemble.ipynb
- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- src/tape/ensemble_readers.py
- tests/tape_tests/conftest.py
- tests/tape_tests/test_ensemble.py
> Save to parquet

- .github/workflows/build-documentation.yml
- .github/workflows/linting.yml
- .github/workflows/testing-and-coverage.yml
Addresses #299. Switched the unit tests, documentation building, and linting to be on all branches. Opted not to for ASV benchmarking, as I don't believe we would want to save benchmarking results until code on the main branch is being affected? Tested this with a demo PR (#346), can see that the CI has been triggered.
> Run CI on all PRs

- .gitignore
- docs/Makefile
- src/tape/analysis/base.py
- src/tape/analysis/stetsonj.py
- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- src/tape/timeseries.py
Addresses a handful of docstring rendering issues.
Also includes some quality-of-life changes while working on documentation: 
- `no-nb` build option now really does ignore notebooks while rendering
- `make no-nb` puts things in the `docs/autoapi` directory, and should be ignored.
> Tidy up some docstrings.

- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble_frame.py
`EnsembleFrame` now extends Dask's [`DataFrame.repartition`](https://docs.dask.org/en/stable/generated/dask.dataframe.DataFrame.repartition.html) to ensure that Ensemble-related metadata is propagated. This closes https://github.com/lincc-frameworks/tape/issues/342
I also replace a call to 
```self.source = self.source.repartition(...)```
with 
```self.update_frame(self.source.repartition(...)``` to ensure that all frame-related tracking data is updated.
> Fix EnsembleFrame.repartition

- docs/tutorials/working_with_the_ensemble.ipynb
- src/tape/ensemble.py
- src/tape/ensemble_frame.py
- src/tape/ensemble_readers.py
- src/tape/utils/__init__.py
- src/tape/utils/utils.py
- tests/tape_tests/test_ensemble.py
- tests/tape_tests/test_ensemble_frame.py
- tests/tape_tests/test_utils.py
Resolves #356. Adds new methods for retrieving a subset of Ensemble data.
I wrote some solution details in #356, but the summary is that this PR adds one new method for returning a subset of objects and their sources, via `Ensemble.sample_objects`. And additionally overwrites the behavior of dasks partition slicing to also set the dirty flag (meaning partition slices will propagate from object to source and vice-versa), making slices on object or source partitions function as another valid method to sample the data.
> Ensemble Methods to retrieve a data subset

- tests/tape_tests/conftest.py
- tests/tape_tests/test_ensemble.py
- tests/tape_tests/test_ensemble_frame.py
- tests/tape_tests/test_feature_extraction.py
Related to #328. This does not resolve the underlying issue, but may reduce the flakiness by not using the client needlessly for many of our tests. I've run the unit test action 3 times and have gotten all passes on all 3 version of python, this seems substantially smoother than the current performance.
Switches most of our unit tests to be clientless, and swaps back a few of the "without_client" tests to now include the client, as it's the new "edge case". I also noticed we were repeating some tests in a parametrize call, so went ahead and removed those.
> Switch to mostly clientless tests

- src/tape/utils/column_mapper/column_mapper.py
- tests/tape_tests/conftest.py
- tests/tape_tests/test_ensemble.py
- tests/tape_tests/test_utils.py
Resolves #185, updates the initial ZTF mapping to use columns from the hipscatted ZTF source catalog. Adds a hipscat kwarg to indicate whether to use the _hipscat_index as the chosen id column, and adds an initial mapper for pan-starrs.
> Update ColumnMapper Known Mappings and Add Hipscat support

- docs/tutorials/binning_slowly_changing_sources.ipynb
- docs/tutorials/scaling_to_large_data.ipynb
- docs/tutorials/structure_function_showcase.ipynb
- docs/tutorials/tape_datasets.ipynb
- docs/tutorials/working_with_structure_function.ipynb
- docs/tutorials/working_with_the_ensemble.ipynb
- docs/tutorials/working_with_the_timeseries.ipynb
- src/tape/ensemble.py
Resolves #377. Updates the docs for consistency
> Switch the Ensemble to default to not using a distributed client

- docs/tutorials/working_with_the_ensemble.ipynb
Addresses #369. I accidentally pushed the first commit of this directly to main. This PR is meant to put a reviewers eyes on the section, and also formally retrigger a readthedocs build.
> add to column selection example

- docs/tutorials.rst
- docs/tutorials/common_data_operations.ipynb
Partially addresses #392 by adding a dedicated notebook for showing a set of dataframe-like operations that we expect users will commonly use with TAPE workflows.
> Common operations tutorial

- docs/gettingstarted/quickstart.ipynb
- docs/tutorials/common_data_operations.ipynb
- docs/tutorials/working_with_the_timeseries.ipynb
A series of minor docs cleanups addressing small changes proposed in https://github.com/lincc-frameworks/tape/issues/372
The following changes are made:
* When loading a time series object in what was formerly [ this section](https://tape.readthedocs.io/en/latest/tutorials/working_with_the_ensemble.html#Inspection), add a sentence such as ``Note that this loads the data from all available bands’’
* Changed ``Installing`` in the Quickstart to be an executable shell command to pip install TAPE
* Demonstrate setting a random seed in `Ensemble.smaple`
* Improves the plot in in[ From the ensemble](https://tape.readthedocs.io/en/latest/tutorials/working_with_the_timeseries.html#From-the-Ensemble)
> Minor docs cleanups for TAPE 

- docs/examples.rst
- docs/gettingstarted.rst
- docs/tutorials.rst
Improves the table of contents view for each of our documentation subsections by just displaying the sections, rather than a full list of all subsections.
> limit depth of toctrees

- docs/gettingstarted/quickstart.ipynb
I noticed that the pip install command in the quickstart guide has a lot of output (potentially because we now use the magic command?). To address this, I've added the quiet flag. Alternatively we could opt to return to using `!pip install lf-tape`
> quiet the quickstart pip install

- docs/tutorials/using_ray_with_the_ensemble.ipynb
The timing comparison takes >5 minutes to build here, making it a disproportionate amount of the doc build time. We've seen timing to be more workflow dependent, so it seems best to just have users test ray if it's interesting to them and let them see the results for themselves.
> remove slow timing comparsion

- docs/tutorials/common_data_operations.ipynb
- src/tape/ensemble_frame.py
- tests/tape_tests/test_ensemble_frame.py
As was pointed out in https://github.com/lincc-frameworks/tape/issues/380, it is not uncommon for partitions to be empty, which can lead to unintuitive results for users since `head` by default only looks at the first partitions.  
To make `head(n)` more intuitive for users we can have it search across all partitions stopping only once there are `n` rows to return.  This differs from Dask behavior where a user must explicitly choose how many partitions to search across.
Warning: this removes the `npartitions` argument previously available in `EnsembleFrame.head` 
Here we iterate over each partition similar to how `head()` until we have found enough rows similar to the [implementation in LSDB](https://github.com/astronomy-commons/lsdb/blob/12271382ee6953c32d4422f0e777d05c0d1bd8f0/src/lsdb/c …
> Have head() traverse all partitions

- docs/tutorials/batch_showcase.ipynb
- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
In https://github.com/lincc-frameworks/tape/issues/409 it was proposed to add a batch helper function `try_batch` which would allow `Ensemble.batch` to be tested on a single lightcurve. To accomplish that goal, here we instead add a new parameter `single_lc` to `Ensemble.batch`
When `single_lc` is provided an object ID, the function provided to `batch` is executed on that single lightcurve.
> Add support for running batch on a single lightcurve

- docs/tutorials/batch_showcase.ipynb
- pyproject.toml
- src/tape/ensemble.py
- tests/tape_tests/test_ensemble.py
Reverts lincc-frameworks/tape#420 and pins dask-expr <1.0.11 to address flakiness reported in https://github.com/lincc-frameworks/tape/issues/434. The plan is to do another PR for the batch single_lc changes in #420 after all of the batch-related flakiness has been addressed. 
Note that even with these changes we're still seeing the test_batch_by_band errors referenced in [lincc-frameworks/tape#434](https://app.slack.com/client/T06D204F2/1.0.11%20to%20address%20flakiness%20reported%20in%20%3Chttps://github.com/lincc-frameworks/tape/issues/434) consistently on the python 3.11.9 build, but this is still an improvement over the current test failures we've been seeing in https://github.com/lincc-frameworks/tape/issues/427
> Pin dask-expr to < 1.10.11 and revert "Add support for running batch on a single lightcurve"

- docs/tutorials/working_with_hipscat_and_lsdb.ipynb
- src/tape/ensemble.py
> add from_legacy_dataframe calls
