.github/workflows/main.yml, lsstseries/analysis/__init__.py, lsstseries/analysis/stetsonj.py, lsstseries/analysis/structurefunction2.py, lsstseries/timeseries.py, test/test.py
Added a structure function functionality. This is a function commonly used to quantify variability of stochastic sources. This is following the algorithm written created by Weixiang Yu (see notebook here: https://github.com/ywx649999311/astro_code/blob/master/variability/SF.ipynb)
I have also included extensive TODO list with the functionality that would need to be included. 
Co-authored-by: Weixiang Yu <wy73@drexel.edu>
=> Added structure function squared functionality

README.md
Added python version to `conda create` so pip will be installed, and added `pip install pytest` for testing.
=> README tweaks for installation.

src/lsstseries/ensemble.py, tests/lsstseries_tests/test_ensemble.py
Addresses #63 , adding the "on" kwarg to Ensemble.batch. Supports multicolumn grouping, and columns from both source and object.
=> Groupby general

src/lsstseries/ensemble.py, tests/lsstseries_tests/test_ensemble.py
I expect this function will mostly be used for testing, but it might also be used for one-off notebook style analysis.
=> Add ability to load an ensemble from a dictionary

src/lsstseries/ensemble.py, tests/lsstseries_tests/test_ensemble.py
Addresses issue #71. Bins the source data during a given time window.
=> Bin data taken during given time-frame

docs/notebooks/working_with_structure_function.ipynb, src/lsstseries/analysis/structure_function/__init__.py, src/lsstseries/analysis/structure_function/base_calculator.py
Adding example to notebook to show how to create and register a new SF subclass.
=> Tutorial to create a new Structure Function subclass

docs/notebooks.rst
=> add notebooks link to binning nb

docs/notebooks/working_with_the_ensemble.ipynb, src/lsstseries/ensemble.py, tests/lsstseries_tests/test_ensemble.py
Change name of `filter` to `query` because it is just wrapping Dask's `query` function.
=> Change name of the filter function to query

docs/notebooks/working_with_the_ensemble.ipynb, src/lsstseries/ensemble.py, tests/lsstseries_tests/test_ensemble.py
Calls Dask's persist on each of the ensemble's tables.
=> Add a persist function to Ensemble

docs/notebooks/working_with_the_ensemble.ipynb, src/lsstseries/ensemble.py, tests/lsstseries_tests/test_ensemble.py
Add a select function that takes a list of columns to keep.
=> Add a basic select function

docs/notebooks/working_with_structure_function.ipynb, src/lsstseries/analysis/__init__.py, src/lsstseries/analysis/light_curve.py, src/lsstseries/analysis/structure_function/__init__.py, src/lsstseries/analysis/structure_function/base_calculator.py, src/lsstseries/analysis/structure_function/basic/calculator.py, src/lsstseries/analysis/structure_function/macleod_2012/calculator.py, src/lsstseries/analysis/structure_function/sf_light_curve.py, src/lsstseries/analysis/structurefunction2.py, tests/lsstseries_tests/structure_function_calculators/test_base_calculator.py, tests/lsstseries_tests/structure_function_calculators/test_bauer_2009a_calculator.py, tests/lsstseries_tests/structure_function_calculators/test_bauer_2009b_calculator.py, tests/lsstseries_tests/structure_function_calculators/test_light_curve.py, tests/lsstseries_tests/structure_function_calculators/test_macleod_2012_calculator.py, tests/lsstseries_tests/structure_function_calculators/test_schmidt_2010_calculator.py, tests/lsstseries_tests/structure_function_calculators/test_sf_light_curve.py
Created `LightCurve` base class that `StructureFunctionLightCurve` inherits from.
Updated references and tests.
=> Create `LightCurve` base class for analysis functions

docs/conf.py, pyproject.toml
"tape" is taken, "lincc-tape" is my proposed alternative
=> update project name for PyPI

.github/workflows/testing-and-coverage.yml
Lingering lsstseries mention in the codecov workflow, breaking the codecov integration.
=> Fix codecov integration

docs/notebooks/working_with_the_ensemble.ipynb, src/tape/ensemble.py, tests/tape_tests/test_ensemble.py
Added the ability to drop NA values from either the source or object table, and now leveraging the Dask Data Frame dropna() function passing along whatever arguments are provided.
=> Issue74 improve dropna

README.md
Adds a readthedocs, Github CI, and codecov badge.
=> Add Repo Badges

docs/tutorials/tape_datasets.ipynb, docs/tutorials/working_with_the_ensemble.ipynb
=> overhaul loading docs

src/tape/ensemble.py, tests/tape_tests/test_ensemble.py
Adds the coalesce function, as described in #176
=> add coalesce

docs/tutorials/binning_slowly_changing_sources.ipynb, docs/tutorials/scaling_to_large_data.ipynb, docs/tutorials/structure_function_showcase.ipynb, docs/tutorials/working_with_structure_function.ipynb, docs/tutorials/working_with_the_ensemble.ipynb, docs/tutorials/working_with_the_timeseries.ipynb, pyproject.toml
Fixes for various typos in the TAPE tutorial notebooks.
We also try to make the plots in structure_function_showcase.ipynb more legible, and we add an additional plot to binning_slowly_changing_sources.ipynb to visualize the binning created by the calculated offset.
The bokeh package is also added to the [dev] dependencies since it's a requirement for the dask client visualizer.
=> Minor fixes of typos and plots for TAPE tutorial

src/tape/ensemble.py
The TAP Query API portion of TAPE has gone unmaintained as we've developed the package. I'm recommending we remove it for now, and reimplement down the road.
=> remove TAP query code for now

pyproject.toml
=> Introduce project.urls in pyproject.toml

README.md
Update the project description for TAPE to better reflect the current state and goals of the project.
=> Update TAPE README.md

pyproject.toml, src/tape/ensemble.py, tests/tape_tests/test_ensemble.py
Another merge of latest changes from main into tape_ensemble_refactor
=> Merge main into tape_ensemble_refactor

src/tape/ensemble.py, src/tape/ensemble_readers.py, src/tape/utils/column_mapper/column_mapper.py, tests/tape_tests/test_ensemble.py, tests/tape_tests/test_utils.py
=> remove provenance machinery for now

src/tape/ensemble.py, tests/tape_tests/test_ensemble.py
Resolves #294 
Adds a a call to sync_tables before calc_nobs is run. And modifies the unit tests for calc_nobs to verify that a sync is performed by the calc_nobs call.
=> Add lazy_sync_tables call to calc_nobs

docs/tutorials.rst
=> initial reorg

docs/_static/custom.css, docs/conf.py, docs/requirements.txt
Changes the sphinx theme to [sphinx book theme](https://sphinx-book-theme.readthedocs.io/en/stable/index.html)
=> Change sphinx theme to book theme

pyproject.toml
=> Update light-curve requirement from <0.8.0,>=0.7.3 to >=0.9.0,<0.10.0

src/tape/ensemble.py
Resolves #405. 
All this needed was the force=True flag to allow light partition expansion when the boundaries don't overlap completely.
=> add force flag to calc_nobs repartitioning

docs/examples/rrlyr-period.ipynb, docs/gettingstarted/quickstart.ipynb, docs/tutorials/batch_showcase.ipynb, docs/tutorials/common_data_operations.ipynb, docs/tutorials/structure_function_showcase.ipynb, docs/tutorials/tape_datasets.ipynb, docs/tutorials/using_ray_with_the_ensemble.ipynb, docs/tutorials/working_with_the_ensemble.ipynb, docs/tutorials/working_with_the_timeseries.ipynb, src/tape/ensemble.py
=> fix divisions warnings
